@startuml

    !include lexakai.theme
    
    title "lexakai-annotations"
    
    artifact kivakit_build_metadata
    artifact lexakai_annotations
    lexakai_annotations --> kivakit_build_metadata
    
@enduml
