@startuml

    !include lexakai.theme
    
    title "lexakai-annotations"
    
    artifact cactus_build_metadata
    artifact lexakai_annotations
    lexakai_annotations --> cactus_build_metadata
    
@enduml
